# Generated by Django 2.0.8 on 2018-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0052_populate_org_uuid")]

    operations = [
        migrations.AddField(
            model_name="org",
            name="webhooks_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether Org can configure RapidPro to send new events to their application"
            ),
        )
    ]
